### ISSUE TITLE
Venter Can Share Site Via Social Media

### ISSUE THREAD

**Issue by conatus** [commonknowledge/vent-your-rent#15]
# User Story
- As a venter
- So that I can convince others there is a renting crisis
- I want to be able to share the manifesto

**Comment by GemCopeland** [comment]
@conatus Here's the email share icon:
[mail.svg.zip](https://github.com/commonknowledge/vent-your-rent/files/3885852/mail.svg.zip)

**Comment by GemCopeland** [comment]
@conatus @janbaykara The share button on the top right isn't hooked up yet

**Comment by conatus** [comment]
@GemCopeland 

Can you make this into a new issue please? Thanks! Can use the label bug.

**Comment by conatus** [comment]
I've disabled the share button for the moment by removing it - https://github.com/commonknowledge/vent-your-rent/commit/337133e58dd0589a7381b5e9ad6016c9e79f4169

**Comment by conatus** [comment]
Add https://github.com/commonknowledge/vent-your-rent/issues/34 to capture
