### ISSUE TITLE
Add divider between two subsequent statistics

### ISSUE THREAD

**Issue by GemCopeland** [commonknowledge/vent-your-rent#19]
Two statistics next to each other feels confusing – it's hard to tell which fact the data belongs to.

I suggest adding a white divider between the two:
<img width="339" alt="Screenshot 2019-11-25 11 39 18" src="https://user-images.githubusercontent.com/2996847/69537747-aa8bc400-0f78-11ea-9f7e-16913fde26c3.png">

**Comment by conatus** [comment]
Will put this in. Can be a modifier of the `<Rule />` component.
