### ISSUE TITLE
As a site visitor longer vents are collapsed and I can read more

### ISSUE THREAD

**Issue by GemCopeland** [commonknowledge/vent-your-rent#20]
# User Story
- As a site visitor
- So I can read vents but also see them in a clear way and get an idea of their volume
- I want a design that allows for longer messages, so collapses them and allows me to read more

# Acceptance Criteria
- [x] Can I post the vent below and see clearly the next vent?
- [x] Can I open up the vent to see all of it and appreciate the scale of the renting crisis?

Some of the vents are incredibly long, e.g.:

```I rented a house in Mistley which was damp, with rotten window frames, draughts and only partial heating. The landlord let himself in while my daughter and I were asleep the night after I moved in and when challenged later told me he didn't know I was there. I'd told him when I was moving in and he had agreed it. Later, he let himself in and painted outside windowsills without telling me (access to the garden was through the house) and I ruined a nice jumper by leaning on the wet gloss paint I hadn't been told about. The landlord decided to partition a bedroom, which was fine, but then asked me to contribute to the cost. I refused.After living there for 6 years, my adult son moved in with me. The landlord told me unless he moved out, I would be given 6 weeks notice to quit. My son worked 9-5, did not have anti social behaviour..just a regular bloke! There was no reason for his attitude. I was threatened with eviction after years of being a model tenant, rent on time, no hassle etc. I voted with my feet and moved 4 years ago. This landlord is one of the most appalling I have ever met in my 35 years of renting houses. He had a reputation for not giving tenants their deposits back, often inventing "damage" he claimed they had caused. I witheld my final month's rent to avoid this. He didn't query this, so either failed to notice or realised he had behaved unreasonably. I wish so much that I had some comeback but fear I don't!```

@GemCopeland to design a version of the results page that displays an excerpt and "Read more" button.

**Comment by GemCopeland** [comment]
<img width="346" alt="Screenshot 2019-11-25 12 55 53" src="https://user-images.githubusercontent.com/2996847/69543421-7cf94780-0f85-11ea-8f33-780374ada5e9.png">

**Comment by conatus** [comment]
@GemCopeland 

Is this also on the Figma file?

**Comment by GemCopeland** [comment]
@conatus Yep, on the far right

**Comment by conatus** [comment]
@janbaykara added some code to truncate text. We need to add this treatment.

https://github.com/commonknowledge/vent-your-rent/pull/41

**Comment by janbaykara** [comment]
Styling for this can be added to WIP PR #41

**Comment by conatus** [comment]
Sorry Jan that was a bit overcooked for me. Went with something a bit more simple.
