### ISSUE TITLE
Renters see a banner to encourage them to register to vote

### ISSUE THREAD

**Issue by conatus** [commonknowledge/vent-your-rent#4]
# User Story
- As a renter
- So I can vote for someone who will make policy changes in the interest of renters
- I want a banner that reminds me to register to vote

# Acceptance Criteria
- Is there a clear banner telling me to register to vote?
- Does it appear when the deadline is still in the future?
- Does it link through to the government voter registration site?

**Comment by conatus** [comment]
@GemCopeland still working up the final banner design.

**Comment by GemCopeland** [comment]
@conatus Figma is updated with the designs now

**Comment by conatus** [comment]
Part of https://github.com/commonknowledge/vent-your-rent/pull/16
