### ISSUE TITLE
Add links to call-to-action buttons

### ISSUE THREAD

**Issue by GemCopeland** [commonknowledge/vent-your-rent#7]
[Email your candidates](https://generationrent.eaction.online/rentermanifesto2019)
[Meet your candidates](https://docs.google.com/forms/d/e/1FAIpQLSdDkCjgIDaY4Bt25LqKPMWMxsa4EYcmd84iCqG21DvgFG5_Ig/viewform)
[Donate](https://www.rentermanifesto.org/donate_to_our_general_election_fund)

**Comment by conatus** [comment]
These are all added to different components.
https://github.com/commonknowledge/vent-your-rent/blob/master/frontend/src/components/ContactCandidateBlock.tsx
https://github.com/commonknowledge/vent-your-rent/blob/master/frontend/src/components/DonationBlock.tsx
