### ISSUE TITLE
Venter can read privacy policy

### ISSUE THREAD

**Issue by GemCopeland** [commonknowledge/vent-your-rent#8]
Privacy

The National Private Tenants Organisation Limited is a company registered in England, number 08731888, operating as Generation Rent. We are committed to safeguarding the privacy of our supporters, members and visitors to www.generationrent.org and www.lettingfees.co.uk. This policy sets out how we will treat your personal information.

1. We collect information about you:

(a) When you give it to us directly

You may give us your personal data when you sign an online form, paper form, online petition, paper petition; when you share information about Generation Rent from our website on Facebook, Twitter and/or via email, when you apply for employment with us, when you apply to volunteer with us, when you contact us by phone, email or post, or when you make payments via our website. We use standardised forms and petitions that allow you to give or withhold your consent to be contacted by Generation Rent.

(b) When you give it to us indirectly

Your information will be provided to us when you follow us or otherwise interact with us on or via Twitter, when you like and/or join our page on Facebook or interact with us in other ways on or via Facebook.

(c) When you give permission to other organisations to share it or it is available publicly

We may combine information you provide to us with information available from external publicly available sources. Depending on your privacy settings for social media services, we may also access information from those accounts or services. We use this information to gain a better understanding of you and to improve our communications and campaigning activities.

(d) When you visit our website 

We use cookies to identify you when you visit our website and to enable us to personalise your online experience (for example by remembering your log-in details if you have them).

(e) When we believe you have a professional interest in our work

We may hold information about you if you are a journalist or officer of a public authority, or are standing for or hold elected office, or have a similar professional interest in the work we do. We may contact you if we believe that you would be interested in our work in the course of your professional duties. Our communications will usually include an option to easily opt out of future communication.

2. Information we collect

We may collect, store and use the following kinds of personal data:

(a) your name, email address, postal address, social media identities, telephone number, and any information that you provide to us for the purpose of subscribing to our emails, becoming a member, or signing a form, a petition or an email to an elected representative or public authority;

(b) information about your computer and about your visits to and use of our website including your IP address, geographical location, browser type, referral source, length of visit and number of page views;

(c) information relating to any interaction or transactions carried out between you and us on or in relation to our website; and

(d) any other information that you choose to send to us.

Applicable law recognises certain categories of personal information as sensitive and therefore requiring more protection, including health information, ethnicity and political opinions. In limited cases, we may collect sensitive personal data about you. We would only collect sensitive personal data if there is a clear reason for doing so; and will only do so with your explicit consent.

3. How we use cookies

The Generation Rent website uses “cookies” to help personalise your online experience. A cookie is a text file that is placed on your computer’s hard drive by a web page server. Cookies cannot be used to run programs or deliver viruses to your computer. Cookies are uniquely assigned to you, and can only be read by a web server in the domain that issued the cookie to you.

One of the primary purposes of cookies is to provide a convenience feature to save you time. The purpose of a cookie is to tell the web server that you have returned to a specific page.

We use Google Analytics to analyse the use of this website. Google Analytics generates statistical and other information about website use by means of cookies, which are stored on users’ computers. The information generated relating to our website is used to create reports about the use of the website. Google will store this information. Google’s privacy policy is available at: http://www.google.com/privacypolicy.html. Social media websites may also send you cookies which track your use of our website.

You have the ability to accept or decline cookies. When you visit our website you will be shown a message that we use cookies, with a link to this page. You can consent to use of cookies while you use the website, or dismiss the message, which will prevent the website from using cookies during your visit.

4. How we use your personal data

Personal data submitted to us will be used for the purposes specified in this privacy policy or in relevant parts of the website.

We may use your personal information to:

(a) administer the website;

(b) improve your experience by personalising the website and communications to you, which may including contacting you about activities relevant to your local area;

(c) enable your use of the services available on the website, including petitions and other campaign activities;

(d) send statements and receipts to you, and collect payments from you;

(e) send you communications about our activities, opportunities and invitations to take part in our activities, including activities involving partner organisations, and fundraising, when you have given us your consent to do so;

(f) send you email, text and telephone notifications which you have specifically requested;

(g) provide third parties with statistical information about our users – but this information will not be used to identify any individual user;

(h) handle the administration of your employment and/or volunteering application;

(i) make petition submissions to third parties, where you have signed the petition and the third party is a target of the campaign to which the petition relates; and/or

(j) deal with enquiries and complaints made by or about you.

Where you submit personal information for publication on our website or elsewhere, we will publish, share and otherwise use that information in accordance with the consent you give us.

We will not sell, rent or share your personal data with third party organisations without your explicit and specific consent.

5. Donations

Donations and membership subscription transactions are handled either through our payment services providers, PayPal and Nationbuilder, or through our bank, Metro Bank PLC. You should only provide your personal information to PayPal after reviewing its privacy policy. We will share information with PayPal only to the extent necessary for the purposes of processing payments you make via our website. We do not store your financial or credit card details.

6. Children’s data

We do not knowingly process data of any person under the age of 16. If we come to discover, or have reason to believe, that you are 15 and under and we are holding your personal information, we will delete that information within a reasonable period and withhold our services accordingly.

7. Other disclosures

In addition to the disclosures reasonably necessary for the purposes identified elsewhere in this privacy policy, we will disclose information about you only when required to do so by law.

8. Security of your personal data

We will take reasonable technical and organisational precautions to prevent the loss, misuse or alteration of your personal information. We store your contact information on our database, which uses Nationbuilder (www.nationbuilder.com), a platform owned by 3DNA Corp, a company registered in the United States. 3DNA Corp maintains a [Privacy Shield](https://nationbuilder.com/privacy_shield) certification with the U.S. Department of Commerce which ensures that its collection and processing of personal data from its customers in the European Union (including us) will be done in accordance with the EU-US Privacy Shield Framework, as described in its [Privacy Shield Notice](https://nationbuilder.com/privacy_shield). 

You are responsible for keeping any login details with which you interact with our website confidential.

9. Your rights

You have the right to be informed how we use your personal information. This privacy notice is designed to do this in a transparent and clear way.

You have the right to view the information we hold about you. You have the right to request the personal information we hold about you in a machine-readable format. You also have the right to request the rectification, restriction, or deletion of the personal information we hold about you.

You have the right not to be subject to automated decision-making processes. This may include using your postal address to send you emails about activities taking place in your region or local area. 

If you make a request that relates to any of the above rights, we will respond within 20 working days. We may request proof of your identity and/or further information in order to process your request. Please e-mail info@generationrent.org. 

There may be circumstances in which these rights do not apply. Further information about your rights, including how to make a complaint about how we handle your data, can be found on the website of the Information Commissioner's Office https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/

10. Lawful processing

There are certain lawful grounds on which we may process your personal information. Those we use are consent, contractual relationships and legitimate interests.

We will email you with news of our campaigns and activities only if you have give us your consent. You can give or withhold your consent to be contacted in this way at any time.

If you have a contractual relationship with us, including if you have signed up as a member, we will communicate with you in relation to this until the contract ends.

If we believe you have a professional interest in our work, i.e. you write, campaign about or make decisions about policies and practices relating to the private rental market in the UK, we will contact you with information we think you will value. We will also rely on this ground if it is not appropriate or practical to ask for your consent.

11. Data Retention

If you withhold your consent to be contacted, we will hold your data, unless you request it to be deleted, or we are required to delete it by law, so that we have a record of previous interactions with you which will help us if you make enquiries in the future. We will delete personal data three years after your most recent interaction with us. We may also delete your information before this period ends if we decide that we have no need to retain it. 

12. Policy amendments

We may update this privacy policy from time-to-time by posting a new version on our website. You should check this page occasionally to ensure you are happy with any changes. We may also notify you of changes to our privacy policy by email.

13. Third party websites

The website and occasionally our emails contain links to other websites. We are not responsible for the privacy policies or practices of third party websites.

14. Unsubscribing

You may unsubscribe from Generation Rent at any time by clicking the unsubscribe link in the footer of any email we send.

15. Contact

We are not required by law to have a Data Protection Officer. If you have any questions about this privacy policy or our treatment of your personal data, please write to us by email info@generationrent.org.

**Comment by conatus** [comment]
Added via link on footer https://github.com/commonknowledge/vent-your-rent/blob/master/frontend/src/components/TakeActionBlock.tsx#L320-L329
